use customer_insights_datacoach;

# 1. What are the names of all the countries in the country table?
select country_name 
from country;

# 2. What is the total number of customers in the customers table?
select count(customer_id) as "Total Customers" 
from customers;

# 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?
select can_email, round(avg(age),2) as Avg_Age 
from customers
where can_email="yes";

# 4. How many orders were made by customers aged 30 or older?
select age, count(order_id) as Total_orders from orders as ord
join customers as cust on ord.customer_id = cust.customer_id
where cust.age >=30
group by age with rollup;

# 5. What is the total revenue generated by each product category?
select products.category,sum(products.price) as Total_revenue from products 
join baskets using(product_id)
group by products.category;


# 6. What is the average price of products in the 'food' category?
select category, round(avg(price),2) as avg_price
from products 
where category = "food";

# 7. How many orders were made in each sales channel (sales_channel column) in the orders table?
select ord.sales_channel, count(b.order_id) as Orders
from orders as ord , baskets as b
where ord.order_id = b.order_id
group by ord.sales_channel;

# 8.What is the date of the latest order made by a customer who can receive marketing emails?
select * from  customers as cust
join orders as ord on  cust.customer_id = ord.customer_id
and cust.can_email = "yes"
order by ord.date_shop;


# 9. What is the name of the country with the highest number of orders?
select c.country_name, count(b.order_id) from country as c, orders as ord, baskets as b
where c.country_id = ord.country_id and ord.order_id = b.order_id
group by c.country_name
limit 1;

# 10. What is the average age of customers who made orders in the 'vitamins' product category?
select p.category,round(avg(cust.age),2) as " avg_age of customer"
from products as p, orders as ord, customers as cust, baskets as b
where b.product_id = p.product_id 
and b.order_id = ord.order_id
and ord.customer_id = cust.customer_id
and p.category = "vitamins";