CREATE TABLE SCHOOL(
SCHOOL_ID VARCHAR(20) NOT NULL PRIMARY KEY,
SCHOOL_NAME VARCHAR(100),
EDUCATION_BOARD VARCHAR(80),
ADDRESS_ID VARCHAR(20)
);

SELECT * FROM SCHOOL;

CREATE TABLE STAFF(
STAFF_ID VARCHAR(20),
STAFF_TYPE VARCHAR(30),
SCHOOL_ID VARCHAR(20),
FIRST_NAME VARCHAR(100) NOT NULL,
LAST_NAME VARCHAR(100) NOT NULL,
AGE INT,
DOB DATE,
GENDER VARCHAR(10) CHECK (GENDER IN('M', 'F')),
JOIN_DATE DATE,
ADDRESS_ID VARCHAR(20),
CONSTRAINT PK_STF PRIMARY KEY(STAFF_ID),
CONSTRAINT FK_STAFF_SCHL FOREIGN KEY(SCHOOL_ID) REFERENCES SCHOOL(SCHOOL_ID),
CONSTRAINT FK_STAFF_ADDR FOREIGN KEY(ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID)
);